# Generated by Selenium IDE : Utilizamos esta automatizacion para comprobar el TC-01 de la historia de usuario del carrito de compra donde podemos verificar no solo que funcione el carrito sino que podemos verificar que funcionen sus imagenes y su texto correctamente.
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAssert2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_assert2(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(974, 1047)
    self.driver.find_element(By.ID, "itemImage").click()
    elements = self.driver.find_elements(By.ID, "productImage")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Add to Cart")
    assert len(elements) > 0
  
